import os
from langchain.agents import create_agent                  #I imported create_agent function from langchain.agents to create agents with specific tools and models. in my older project I used the create_react_agent because I used old langchain, in this projects i used create_agent because I used new langchain version.
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from src.tools.tools import web_search, scrape_url
from dotenv import load_dotenv



load_dotenv()



OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
# Model Initialization
llm = ChatOpenAI(
    model="openai/gpt-4o-mini",
    temperature=0,
    api_key=OPENAI_API_KEY,
    base_url="https://openrouter.ai/api/v1",
    max_tokens=1500
)


# 1st Agent : (search_agent)use (Tool1) (tavily_api)live web results  to extract the URLs and snippets of relevant information on the research topic. This agent will use the web_search tool to fetch recent and reliable information from the web.
def build_search_agent():                        #Extract URL from web pages 
    return create_agent(
        model= llm,
        tools=[web_search],
       
    )


# 2nd Agent : (Reader Agent) use (Tool2) (Beautifulsoup)scrapes pages  to read and extract information from URLs found by search agent. This agent will use the scrape_url tool to fetch content from the web pages and extract relevant information for the research topic.
def build_reader_agent():                        #Extract content from the URLs found by search agent
    return create_agent(
        model= llm,
        tools=[scrape_url],
        system_prompt="""
You are a specialized Reader Agent.

You must:
1. Identify the most relevant URL from the search results.
2. Always call the scrape_url tool.
3. Extract factual content from the webpage.
4. Return the extracted information only.

Never:
- Ask follow-up questions.
- Ask for confirmation.
- Explain what you plan to do.
- Refuse to scrape a URL.

Your final response must contain the scraped content.
"""
    )


#writer chain (LCEL chain) (3rd agent) to compile the research findings into a structured report. This agent will take the gathered research and produce a well-organized report with an introduction, key findings, conclusion and sources.
#Write the report based on the research gathered by the search and reader agents. 
writer_prompt = ChatPromptTemplate.from_messages([                                                        #custom prompt for the writer agent to structure the report based on the research gathered. The prompt instructs the agent to write a detailed research report with specific sections and to list all sources used in the research.
    ("system", "You are an expert research writer. Write clear, structured and insightful reports."),
    ("human", """Write a detailed research report on the topic below.

Topic: {topic}

Research Gathered:
{research}

Structure the report as:
- Introduction
- Key Findings (minimum 3 well-explained points)
- Conclusion
- Sources (list all URLs found in the research)

Be detailed, factual and professional."""),
])

writer_chain = writer_prompt | llm | StrOutputParser()      #writer_prompt will goes to llm , llm will try to work on that llm expecting topic and reasrch




#critic_chain (4th agent) to review the report generated by writer chain and provide feedback for improvement. This will help in refining the report iteratively.

critic_prompt = ChatPromptTemplate.from_messages([
     ("system", "You are a sharp and constructive research critic. Be honest and specific."),
    ("human", """Review the research report below and evaluate it strictly.

Report:
{report}

Respond in this exact format:

Score: X/10

Strengths:
- ...
- ...

Areas to Improve:
- ...
- ...

One line verdict:
..."""),
])

critic_chain = critic_prompt | llm | StrOutputParser()         #strOuputparser() will parse the output from the critic chain to extract the score, strengths, areas for improvement and the one line verdict in a structured format that can be easily interpreted and used for further refinement of the report.

