from src.agents.agents import build_search_agent, build_reader_agent, writer_chain, critic_chain


#creating the function that will run the entire research pipeline. This function will orchestrate the interactions between the search agent, reader agent, writer chain and critic chain to produce a comprehensive research report on the given topic. The function will return a dictionary containing the search results, scraped content, final report and critic feedback for further analysis and improvement.
def run_research_pipeline(topic : str) -> dict:

    state = {}

    #search agent working 
    print("\n"+" ="*50)
    print("step 1 - search agent is working ...")
    print("="*50)

    search_agent = build_search_agent()
    search_result = search_agent.invoke({
        "messages" : [("user", f"Find recent, reliable and detailed information about: {topic}")]
    })
    state["search_results"] = search_result['messages'][-1].content         #state memory to store the search results for later use by the reader agent and writer chain. The search results will be used as input for the reader agent to scrape relevant content from the URLs found and also as part of the research material for the writer chain to draft the final report.

    print("\n search result ",state['search_results'])


    #step 2 - reader agent 
    print("\n"+" ="*50)
    print("step 2 - Reader agent is scraping top resources ...")
    print("="*50)

    reader_agent = build_reader_agent()
    reader_result = reader_agent.invoke({
        "messages": [("user",
            f"Based on the following search results about '{topic}', "
            f"pick the most relevant URL and scrape it for deeper content.\n\n"
            f"Search Results:\n{state['search_results'][:800]}"                     #scraped content from url now stored in state memory
        )]
    })

    state['scraped_content'] = reader_result['messages'][-1].content

    print("\nscraped content: \n", state['scraped_content'])


    #step 3 - writer chain 

    print("\n"+" ="*50)
    print("step 3 - Writer is drafting the report ...")
    print("="*50)

    research_combined = (
        f"SEARCH RESULTS : \n {state['search_results']} \n\n"
        f"DETAILED SCRAPED CONTENT : \n {state['scraped_content']}"
    )

    state["report"] = writer_chain.invoke({              #written content also stored in state memory for later use by the critic chain to review and provide feedback on the report. 
        "topic": topic,
        "research" : research_combined
    })

    print("\n Final Report\n",state['report'])


    #critic report 

    print("\n"+" ="*50)
    print("step 4 - critic is reviewing the report ")
    print("="*50)

    state["feedback"] = critic_chain.invoke({         #the critic chain will review the final report generated by the writer chain and provide feedback for improvement. The feedback will include a score, strengths, areas for improvement and a one line verdict. This feedback will be stored in the state memory for analysis and to guide further refinement of the report if needed.
        "report":state['report']
    })

    print("\n critic report \n", state['feedback'])

    return state
